### ISSUE TITLE
Widget not being added to project

### ISSUE THREAD

**Issue by khant21** [Sitefinity/Sitefinity-VSIX#10]
I am trying to create a new widget with VS VSIX. I am right clicking my SitefinityWebApp and adding a new item. I go to the 'Sitefinity' tab and click Widget. A black terminal screen appears for a second then disappears. I have tried refreshing the project, rebuilding, uninstalling and installing vsix again, nothing has worked.

If this is an ongoing bug, is there any other resource or method I can use to efficiently create new custom widgets in mvc?

Thanks

**Comment by jonathanread** [comment]
Does it make any difference if you run VS as an Admin?

**Comment by annix8** [comment]
Hello @khant21 , 

Thank you for the feedback. We have introduced this functionality in the Sitefinity-CLI - version 1.0.0.7 which was released on Jun 18. And since the VSIX is based on the Sitefinity-CLI, you should be able to see your newly added widget files in your solution upon creation.

Regards
